[versions]
kotlin = "2.0.20"
compose = "1.7.0-beta02"
coroutines = "1.9.0-RC.2"

sqldelight = "2.0.2"

vinceglb-filekit = "0.7.0"

#dokka = "1.9.20"

# Android
androidGradlePlugin = "8.6.0-alpha07"

ksp = "2.0.20-1.0.25"
hilt = "2.52"

[libraries]
# Common
coroutines =   { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

#jetbrains-androidx-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "compose"}
jetbrains-compose-material-navigation = { group = "org.jetbrains.compose.material", name = "material-navigation", version.ref = "compose"}

filekit-core = { group = "io.github.vinceglb", name = "filekit-core", version.ref = "vinceglb-filekit" }
filekit-compose = { group = "io.github.vinceglb", name = "filekit-compose", version.ref = "vinceglb-filekit" }

sqldelight-runtime =  { group = "app.cash.sqldelight", name = "runtime", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }

# Desktop
sqldelight-driver-jvm = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }

# Android
sqldelight-driver-android  = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }

[plugins]
# KMP
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
# Kotlin interop compiler plugin
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
#Compose Multiplatform BOM plugin
jetbrains-compose-kmpbom = { id = "org.jetbrains.compose", version.ref = "compose" }

jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
#jetbrains-kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

# Android
jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
google-android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
google-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

[bundles]
common-sqldelight = ["sqldelight-runtime", "sqldelight-coroutines-extensions"]
common-filekit = ["filekit-core", "filekit-compose"]
